In [1]:
import numpy as np

In [2]:
# data
x = np.array([2.5, 0.3, 2.8, 0.5])
y = np.array([1, -1, 1, 1])

In [3]:
# model
w0 = 0
w1 = 1
y_hat = w0 + w1*x

y_hat

array([2.5, 0.3, 2.8, 0.5])

In [4]:
# model
def f(x, w=np.array([w0, w1])):
    return w[0] + w[1]*x


# P[y = +1 | x,w] = sigmoid(f(x,w))
def sigmoid(x):
    f_x = f(x)
    return 1.0 / (1.0 + np.exp(-f(x)))
    

# P(y | x,w)
#     P[y = +1 | x,w] = sigmoid(f(x,w))
#     P[y = -1 | x,w] = 1 - sigmoid(f(x,w))
def P(y, x):
    f_x = f(x)
    if y == 1:
        return 1.0 / (1.0 + np.exp(-f_x))
    else:
        return np.exp(-f_x) / (1.0 + np.exp(-f_x))


# Unit function: 
#     1[y = c] = 1 if y == c
#     1[y = c] = 0 if y != c
def unit(y, c=1):
    if y == c:
        return 1
    else:
        return 0

### Calculate the likelihood of this data

In [5]:
likelihoods = np.array([P(y[i], x[i]) for i in range(4)])
likelihoods

array([0.92414182, 0.42555748, 0.94267582, 0.62245933])

In [6]:
data_likelihood = likelihoods.prod()
data_likelihood

0.2307651414741412

### Calculate the derivative of the log likelihood 

In [7]:
derivative_log_likelihoods = np.array([ x[i] * (unit(y[i], 1) - sigmoid(x[i])) for i in range(4)])
derivative_log_likelihoods

array([ 0.18964545, -0.17233276,  0.16050769,  0.18877033])

In [8]:
data_derivative_log_likelihood = derivative_log_likelihoods.sum()
data_derivative_log_likelihood

0.36659072192551606