In [1]:
import tensorflow as tf
print(tf.__version__)

1.9.0


## String

In [2]:
hello = tf.constant('Hello')
world = tf.constant('World')

with tf.Session() as sess:
    result = sess.run(hello+world)
    
result

b'HelloWorld'

## Number

In [3]:
a = tf.constant(10)
b = tf.constant(200)

with tf.Session() as sess:
    result = sess.run(a + b)
    
result

210

## Operations

In [4]:
# Constant
const = tf.constant(10)

# Mat filled w/ 10s
fill_mat = tf.fill((4,4),10)

# Mat filled w/ 0s
myzeros = tf.zeros((4,4))

# Mat filled w/ 1s
myones = tf.ones((4,4))

# Mat filled w/ Random
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

# Mat filled w/ uniform Random
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [5]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

# Interactive Session: Only run once
sess = tf.InteractiveSession()

for op in my_ops:
    print(op.eval())
    print('\n')

# Close session
sess.close()

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.14865346  0.30599102  0.36659086  0.02619975]
 [-0.19783275 -0.73391676 -1.2572029  -0.77519697]
 [-0.76914954 -0.15557016 -0.29275414  0.0963235 ]
 [ 0.21194763 -0.00973291 -0.17542823 -0.64273256]]


[[0.85109544 0.87970245 0.80631304 0.7696302 ]
 [0.7881911  0.48106408 0.06596744 0.91635954]
 [0.8750869  0.5147828  0.10615396 0.83634615]
 [0.46925557 0.7229183  0.20447648 0.75797665]]




## Matrix Multiplication

In [6]:
a = tf.constant([
    [1,2],
    [3,4]])

a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [7]:
b = tf.constant([
    [10],
    [100]])

b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [8]:
result = tf.matmul(a,b)

# Interactive Session: Only run once
sess = tf.InteractiveSession()

print(result.eval())

# Close session
sess.close()

[[210]
 [430]]


## TF Graph

In [9]:
n1 = tf.constant(1)
n2 = tf.constant(2)

n3 = n1 + n2

In [10]:
# Using with auto-closes the session
with tf.Session() as sess:
    result = sess.run(n3)

print(result)

3


## Variables and Placeholders
- 2 main types of tensor objects

#### Variables
- Hold the values of weights and biases
- Need to be intialized

#### Placeholders
- Empty at first
- Need to declare an expected data type and shape

In [11]:
sess = tf.InteractiveSession()

In [12]:
# Variables
my_tensor = tf.random_uniform((4,4),0,1)
my_var = tf.Variable(initial_value=my_tensor)

# Note! You must initialize all global variables!
# This line is really important, it is easy to forget!
init = tf.global_variables_initializer()
init.run()

# Get var
my_var.eval()

array([[0.22862709, 0.4848169 , 0.5512451 , 0.51062477],
       [0.40958226, 0.21581757, 0.9028933 , 0.1457498 ],
       [0.5064626 , 0.9935864 , 0.593148  , 0.01095259],
       [0.69394433, 0.33920944, 0.30559456, 0.48190522]], dtype=float32)

In [13]:
sess.run(my_var)

array([[0.22862709, 0.4848169 , 0.5512451 , 0.51062477],
       [0.40958226, 0.21581757, 0.9028933 , 0.1457498 ],
       [0.5064626 , 0.9935864 , 0.593148  , 0.01095259],
       [0.69394433, 0.33920944, 0.30559456, 0.48190522]], dtype=float32)

In [14]:
# Placeholders
ph = tf.placeholder(
    tf.float32,        # Data type
    shape=(None,5))    # shape

In [15]:
sess.close()