In [1]:
import numpy as np

In [2]:
from sympy import *

In [3]:
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')

x1_ = Symbol('x1_')
x2_ = Symbol('x2_')
x3_ = Symbol('x3_')

u1 = Symbol('u1')
u2 = Symbol('u2')

u1_ = Symbol('u1_')
u2_ = Symbol('u2_')

t = Symbol('t')

### 1. calculate the expression $\frac{df}{dt} = \frac{\partial f}{\partial \mathbf{x}} \frac{d\mathbf{x}}{dt}$ where:
$$f(\mathbf{x}) = f(x_1, x_2) =x_1^2x_2^2 + x_1x_2$$
$$\mathbf{x} = (x_1, x_2)$$
$$x_1(t)  =1-t^2$$
$$x_2(t)  =1+t^2$$

In [4]:
f = x1_**2 * x2_**2 + x1_*x2_
x1 = 1 - t**2
x2 = 1 + t**2

In [5]:
np.array([diff(f, x1_), diff(f, x2_)])

array([2*x1_*x2_**2 + x2_, 2*x1_**2*x2_ + x1_], dtype=object)

In [6]:
np.array([diff(x1, t), diff(x2, t)])

array([-2*t, 2*t], dtype=object)

$$\frac{df}{dt} = \frac{\partial f}{\partial \mathbf{x}} \frac{d\mathbf{x}}{dt} = [2x_1x_2^2 + x_2, 2x_1^2x_2 + x_1] \begin{bmatrix} -2t \\ 2t \end{bmatrix}$$

In [7]:
df =  np.array([
    diff(f, x1_).subs({x1_:x1, x2_:x2}),
    diff(f, x2_).subs({x1_:x1, x2_:x2})])
dx = np.array([diff(x1, t), diff(x2, t)])

res = np.dot(df,dx)
simplify(res)

t**3*(8*t**4 - 12)

### 2. For the following functions, calculate the expression $\frac{df}{dt} = \frac{\partial f}{\partial \mathbf{x}} \frac{d\mathbf{x}}{dt}$ in matrix form, where x = (x1, x2)
$$f(\mathbf{x}) = f(x_1, x_2, x_3) =x_1^3cos(x_2)e^{x_3}$$
$$x_1(t) = 2t$$
$$x_2(t) = 1-t^2$$
$$x_3(t) = e^t$$

In [8]:
f = x1_**3 * cos(x2_) * exp(x3_)
x1 = 2*t
x2 = 1 - t**2
x3 = exp(t)

In [9]:
np.array([diff(f, x1_), diff(f, x2_), diff(f, x3_)])

array([3*x1_**2*exp(x3_)*cos(x2_), -x1_**3*exp(x3_)*sin(x2_),
       x1_**3*exp(x3_)*cos(x2_)], dtype=object)

In [10]:
np.array([diff(x1, t), diff(x2, t), diff(x3, t)])

array([2, -2*t, exp(t)], dtype=object)

$$\frac{df}{dt} = \frac{\partial f}{\partial \mathbf{x}} \frac{d\mathbf{x}}{dt} = [3x_1^2cos(x_2)e^{x_3}, -x_1^3sin(x_2)e^{x_3}, x_1^3cos(x_2)e^{x_3}] \begin{bmatrix} 2 \\ -2t \\ e^t \end{bmatrix}$$

In [11]:
df = np.array([
        diff(f, x1_).subs({x1_:x1, x2_:x2, x3_:x3}),
        diff(f, x2_).subs({x1_:x1, x2_:x2, x3_:x3}),
        diff(f, x3_).subs({x1_:x1, x2_:x2, x3_:x3})])
dx = np.array([diff(x1, t), diff(x2, t), diff(x3, t)])

res = np.dot(df, dx)
simplify(res)

8*t**2*(-2*t**2*sin(t**2 - 1) + t*exp(t)*cos(t**2 - 1) + 3*cos(t**2 - 1))*exp(exp(t))

### 3. For the following functions, calculate the expression $\frac{df}{dt} = \frac{\partial f}{\partial \mathbf{x}} \frac{\partial \mathbf{x}}{\partial \mathbf{u}} \frac{d\mathbf{u}}{dt}$ in matrix form, where x=(x1,x2) and u=(u1,u2)
$$f(\mathbf{x}) = f(x_1, x_2) = x_1^2 - x_2^2$$
$$x_1(u_1, u_2) = 2u_1 + 3u_2$$
$$x_2(u_1, u_2) =2u_1 -3u_2$$
$$u_1(t) = cos(t/2)$$
$$u_2(t) = sin(2t)$$

In [12]:
f = x1_**2 - x2_**2
x1 = 2*u1_ + 3*u2_
x2 = 2*u1_ - 3*u2_
u1 = cos(t/2)
u2 = sin(2*t)

In [13]:
np.array([diff(f, x1_), diff(f, x2_)])

array([2*x1_, -2*x2_], dtype=object)

In [14]:
np.array([
    [diff(x1, u1_), diff(x1, u2_)],
    [diff(x2, u1_), diff(x2, u2_)]])

array([[2, 3],
       [2, -3]], dtype=object)

In [15]:
np.array([diff(u1, t), diff(u2, t)])

array([-sin(t/2)/2, 2*cos(2*t)], dtype=object)

$$\frac{df}{dt} =\frac{\partial f}{\partial \mathbf{x}} \frac{\partial \mathbf{x}}{\partial \mathbf{u}} \frac{d\mathbf{u}}{dt} = [2x_1, -2x_2] \begin{bmatrix} 2 & 3 \\ 2 & -3  \end{bmatrix} \begin{bmatrix} -sin(t/2)/2 \\ 2cos(2t) \end{bmatrix}$$

In [16]:
df = np.array([
        diff(f, x1_).subs({x1_:x1, x2_:x2}).subs({u1_:u1, u2_:u2}),
        diff(f, x2_).subs({x1_:x1, x2_:x2}).subs({u1_:u1, u2_:u2})])
dx = np.array([
    [diff(x1, u1_).subs({u1_:u1, u2_:u2}), diff(x1, u2_).subs({u1_:u1, u2_:u2})],
    [diff(x2, u1_).subs({u1_:u1, u2_:u2}), diff(x2, u2_).subs({u1_:u1, u2_:u2})]])
du = np.array([
    diff(u1, t),
    diff(u2, t)])

res = np.dot(np.dot(df, dx), du)
simplify(res)

18*cos(3*t/2) + 30*cos(5*t/2)

### 4. For the following functions, calculate the expression $\frac{df}{dt} = \frac{\partial f}{\partial \mathbf{x}} \frac{\partial \mathbf{x}}{\partial \mathbf{u}} \frac{d\mathbf{u}}{dt}$ in matrix form, where x=(x1,x2) and u=(u1,u2)
$$f(\mathbf{x}) = f(x_1, x_2) = cos(x_1)sin(x_2)$$
$$x_1(u_1, u_2) = 2u_1^2 + 3u_2^2 -u_2$$
$$x_2(u_1, u_2) =2u_1 -5u_2^3$$
$$u_1(t) = e^{t/2}$$
$$u_2(t) = e^{-2t}$$

In [17]:
f = cos(x1_) * sin(x2_)
x1 = 2*u1_**2 + 3*u2_**2 - u2_
x2 = 2*u1_ - 5*u2_**3
u1 = exp(t/2)
u2 = exp(-2*t)

In [18]:
np.array([diff(f, x1_), diff(f, x2_)])

array([-sin(x1_)*sin(x2_), cos(x1_)*cos(x2_)], dtype=object)

In [19]:
np.array([
    [diff(x1, u1_), diff(x1, u2_)],
    [diff(x2, u1_), diff(x2, u2_)]])

array([[4*u1_, 6*u2_ - 1],
       [2, -15*u2_**2]], dtype=object)

In [20]:
np.array([diff(u1, t), diff(u2, t)])

array([exp(t/2)/2, -2*exp(-2*t)], dtype=object)

$$\frac{df}{dt} =\frac{\partial f}{\partial \mathbf{x}} \frac{\partial \mathbf{x}}{\partial \mathbf{u}} \frac{d\mathbf{u}}{dt} = [-sin(x_1)sin(x_2), cos(x_1)cos(x_2)] \begin{bmatrix} 4u_1 & 6u_2 - 1 \\ 2 & -15u_2^2 \end{bmatrix} \begin{bmatrix} e^{t/2}/2 \\ -2e^{-2t} \end{bmatrix}$$

In [21]:
df = np.array([
        diff(f, x1_).subs({x1_:x1, x2_:x2}).subs({u1_:u1, u2_:u2}),
        diff(f, x2_).subs({x1_:x1, x2_:x2}).subs({u1_:u1, u2_:u2})])
dx = np.array([
    [diff(x1, u1_).subs({u1_:u1, u2_:u2}), diff(x1, u2_).subs({u1_:u1, u2_:u2})],
    [diff(x2, u1_).subs({u1_:u1, u2_:u2}), diff(x2, u2_).subs({u1_:u1, u2_:u2})]])
du = np.array([
    diff(u1, t),
    diff(u2, t)])

res = np.dot(np.dot(df, dx), du)
simplify(res)

((-2*exp(t/2)*sin(2*exp(t/2) - 5*exp(-6*t))*sin(2*exp(t) - exp(-2*t) + 3*exp(-4*t)) + cos(2*exp(t/2) - 5*exp(-6*t))*cos(2*exp(t) - exp(-2*t) + 3*exp(-4*t)))*exp(17*t/2) - 2*(exp(2*t) - 6)*exp(4*t)*sin(2*exp(t/2) - 5*exp(-6*t))*sin(2*exp(t) - exp(-2*t) + 3*exp(-4*t)) + 30*exp(2*t)*cos(2*exp(t/2) - 5*exp(-6*t))*cos(2*exp(t) - exp(-2*t) + 3*exp(-4*t)))*exp(-8*t)

### 5. For the following functions, calculate the expression $\frac{df}{dt} = \frac{\partial f}{\partial \mathbf{x}} \frac{\partial \mathbf{x}}{\partial \mathbf{u}} \frac{d\mathbf{u}}{dt}$ in matrix form, where x=(x1,x2) and u=(u1,u2).
$$f(\mathbf{x}) = f(x_1, x_2, x_3) = sin(x_1)cos(x_2)e^{x_3}$$
$$x_1(u_1, u_2) = sin(u_1) + cos(u_2)$$
$$x_2(u_1, u_2) = cos(u_1) - sin(u_2)$$
$$x_3(u_1, u_2) = e^{u_1 + u_2}$$
$$u_1(t) = 1 + t/2$$
$$u_2(t) = 1 - t/2$$

In [22]:
f = sin(x1_)*cos(x2_)*exp(x3_)
x1 = sin(u1_) + cos(u2_)
x2 = cos(u1_) - sin(u2_)
x3 = exp(u1_ + u2_)
u1 = 1 + t/2
u2 = 1 - t/2

In [23]:
np.array([diff(f, x1_), diff(f, x2_), diff(f, x3_)])

array([exp(x3_)*cos(x1_)*cos(x2_), -exp(x3_)*sin(x1_)*sin(x2_),
       exp(x3_)*sin(x1_)*cos(x2_)], dtype=object)

In [24]:
np.array([
    [diff(x1, u1_), diff(x1, u2_)],
    [diff(x2, u1_), diff(x2, u2_)],
    [diff(x3, u1_), diff(x3, u2_)]])

array([[cos(u1_), -sin(u2_)],
       [-sin(u1_), -cos(u2_)],
       [exp(u1_ + u2_), exp(u1_ + u2_)]], dtype=object)

In [25]:
np.array([diff(u1, t), diff(u2, t)])

array([1/2, -1/2], dtype=object)

$$[cos(x_1)cos(x_2)e^{x_3}, -sin(x_1)sin(x_2)e^{x_3}, sin(x_1)cos(x_2)e^{x_3}] \begin{bmatrix} cos(u_1) & -sin(u_2) \\ -sin(u_1) & -cos(u_2) \\ e^{u_1 + u_2} & e^{u_1 + u_2} \end{bmatrix} \begin{bmatrix} 1/2 \\ -1/2 \end{bmatrix}$$

In [26]:
df = np.array([
        diff(f, x1_).subs({x1_:x1, x2_:x2, x3_:x3}).subs({u1_:u1, u2_:u2}),
        diff(f, x2_).subs({x1_:x1, x2_:x2, x3_:x3}).subs({u1_:u1, u2_:u2}),
        diff(f, x3_).subs({x1_:x1, x2_:x2, x3_:x3}).subs({u1_:u1, u2_:u2})])
dx = np.array([
    [diff(x1, u1_).subs({u1_:u1, u2_:u2}), diff(x1, u2_).subs({u1_:u1, u2_:u2})],
    [diff(x2, u1_).subs({u1_:u1, u2_:u2}), diff(x2, u2_).subs({u1_:u1, u2_:u2})],
    [diff(x3, u1_).subs({u1_:u1, u2_:u2}), diff(x3, u2_).subs({u1_:u1, u2_:u2})]])
du = np.array([
    diff(u1, t),
    diff(u2, t)])

res = np.dot(np.dot(df, dx), du)
simplify(res)

(-sin(t/2 - 1)*cos(sin(t/2 - 1) + cos(t/2 + 1))*cos(sin(t/2 + 1) + cos(t/2 - 1)) + sin(t/2 + 1)*sin(sin(t/2 - 1) + cos(t/2 + 1))*sin(sin(t/2 + 1) + cos(t/2 - 1)) - sin(sin(t/2 - 1) + cos(t/2 + 1))*sin(sin(t/2 + 1) + cos(t/2 - 1))*cos(t/2 - 1) + cos(t/2 + 1)*cos(sin(t/2 - 1) + cos(t/2 + 1))*cos(sin(t/2 + 1) + cos(t/2 - 1)))*exp(exp(2))/2