In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

1.6.0
True


## 1. Tensors
- Same as numpy

In [2]:
# scala
t0 = torch.tensor(4.)

print(t0)
print(t0.dtype)
print(t0.shape)

tensor(4.)
torch.float32
torch.Size([])


In [3]:
# Vector
t1 = torch.tensor([1., 2, 3, 4])

print(t1)
print(t1.dtype)
print(t1.shape)

tensor([1., 2., 3., 4.])
torch.float32
torch.Size([4])


In [4]:
# Matrix
t2 = torch.tensor(
    [[5., 6], 
     [7, 8], 
     [9, 10]])

print(t2)
print(t2.dtype)
print(t2.shape)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
torch.float32
torch.Size([3, 2])


In [5]:
# 3-D tensor
t3 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])

print(t3)
print(t3.dtype)
print(t3.shape)

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])
torch.float32
torch.Size([2, 2, 3])


## 2. Tensor Operations

In [6]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [7]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

#### Compute Gradients

In [8]:
# The derivates of the input tensors are stored in the .grad property
y.backward()

# Display gradients
print('dy/dx:', x.grad) # None becoz x requires_grad=False
print('dy/dw:', w.grad) # dy/dw = x
print('dy/db:', b.grad) # dy/db = 1

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


## 3. Numpy array <-> torch tensor

In [9]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])

print(x)
print(x.shape)
print(x.dtype)

[[1. 2.]
 [3. 4.]]
(2, 2)
float64


In [10]:
# np array -> torch tensor
y = torch.from_numpy(x)

print(y)
print(y.shape)
print(y.dtype)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
torch.Size([2, 2])
torch.float64


In [11]:
# torch tensor -> np array
z = y.numpy()

print(z)
print(z.shape)
print(z.dtype)

[[1. 2.]
 [3. 4.]]
(2, 2)
float64
