In [1]:
import torch
import numpy as np

# 1. Create torch tensor

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6926, 0.5327, 0.4205],
        [0.2039, 0.8113, 0.1510],
        [0.5618, 0.6669, 0.2317],
        [0.8417, 0.1594, 0.0145],
        [0.8905, 0.0748, 0.3024]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


#### Create based on existing tensors

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[-1.0470, -0.1390, -0.6880],
        [-0.2868, -1.7175, -0.2800],
        [-0.2782, -1.0331, -0.2068],
        [-0.2238, -0.7491, -0.4614],
        [ 0.7169,  1.2641, -1.2818]])


# 2. Attributes

In [8]:
# Get shape
print(x.size())

torch.Size([5, 3])


In [9]:
# slice
print(x[:, 1])

tensor([-0.1390, -1.7175, -1.0331, -0.7491,  1.2641])


# 3. Operations

In [10]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

#### ops

In [11]:
print(x + y)
print(torch.add(x, y))

tensor([[1.7090, 0.6432, 1.1329],
        [0.2694, 0.3478, 0.5612],
        [1.3530, 1.1800, 0.5946],
        [0.9444, 0.5512, 0.9898],
        [1.0129, 1.4179, 1.1429]])
tensor([[1.7090, 0.6432, 1.1329],
        [0.2694, 0.3478, 0.5612],
        [1.3530, 1.1800, 0.5946],
        [0.9444, 0.5512, 0.9898],
        [1.0129, 1.4179, 1.1429]])


In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.7090, 0.6432, 1.1329],
        [0.2694, 0.3478, 0.5612],
        [1.3530, 1.1800, 0.5946],
        [0.9444, 0.5512, 0.9898],
        [1.0129, 1.4179, 1.1429]])


#### inplace

In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[1.7090, 0.6432, 1.1329],
        [0.2694, 0.3478, 0.5612],
        [1.3530, 1.1800, 0.5946],
        [0.9444, 0.5512, 0.9898],
        [1.0129, 1.4179, 1.1429]])


# 4. Manipulations

In [14]:
x = torch.randn(4, 4)
x.size()

torch.Size([4, 4])

#### Reshape

In [15]:
print(x.view(16).size())
print(x.view(-1, 8).size())  # the size -1 is inferred from other dimensions

torch.Size([16])
torch.Size([2, 8])


#### 1 element tensor -> scalar

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5307])
0.5306511521339417


In [17]:
x = torch.randn(1,1)
print(x)
print(x.item())

tensor([[0.9868]])
0.9867517352104187


# 5. Interact with numpy 

#### torch tensor -> numpy

In [18]:
a = torch.ones(5)
b = a.numpy()

print(a.size(), b.shape)

torch.Size([5]) (5,)


#### numpy -> torch tensor

In [19]:
a = np.ones(5)
b = torch.from_numpy(a)

print(a.shape, b.size())

(5,) torch.Size([5])


# 6. Cuda tensor

In [20]:
# Create a tensor on cpu
x = torch.randn(5, 3)

# Check if tensor is in cpu or gpu
print(f"x is on: {x.device}")

# CUDA code
if torch.cuda.is_available():
    # a CUDA device object
    device = torch.device("cuda")

    # Directly create a tensor on GPU
    y = torch.ones_like(x, device=device)
    print(f"y is on: {x.device}")

    # Move from cpu -> gpu
    x = x.to(device)
    print(f"Now, x is on: {x.device}")

    # Do ops
    z = x + y
    print(z)

# Bring z to cpu
z = z.to("cpu", torch.double)
print(z)

x is on: cpu
y is on: cpu
Now, x is on: cuda:0
tensor([[ 1.8399, -1.2654, -0.4586],
        [-0.1287,  1.9742,  2.8434],
        [-0.2948,  3.1158,  0.4546],
        [-0.3405,  0.8449,  1.0437],
        [ 0.5920,  2.5526,  0.6229]], device='cuda:0')
tensor([[ 1.8399, -1.2654, -0.4586],
        [-0.1287,  1.9742,  2.8434],
        [-0.2948,  3.1158,  0.4546],
        [-0.3405,  0.8449,  1.0437],
        [ 0.5920,  2.5526,  0.6229]], dtype=torch.float64)
