In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('data/flags.csv', delimiter=',')
display(df.head())

name  landmass  zone  area  population  language  religion  bars  \
0     Afghanistan         5     1   648          16        10         2     0   
1         Albania         3     1    29           3         6         6     0   
2         Algeria         4     1  2388          20         8         2     2   
3  American-Samoa         6     3     0           0         1         1     0   
4         Andorra         3     1     0           0         6         0     3   

   stripes  colours  ...  saltires  quarters  sunstars  crescent  triangle  \
0        3        5  ...         0         0         1         0         0   
1        0        3  ...         0         0         1         0         0   
2        0        3  ...         0         0         1         1         0   
3        0        5  ...         0         0         0         0         1   
4        0        3  ...         0         0         0         0         0   

   icon  animate text  topleft  botright  
0     1        0    0    black     green  
1     0        1    0      red       red  
2     0        0    0    green     white  
3     1        1    0     blue       red  
4     0        0    0     blue       red  

[5 rows x 30 columns]

## Question 1

- Consider two events:
    + A: this flag has no circles
    + B: this flag has no bars
- Find P(A∣B)

In [3]:
df['bars'].value_counts()

0    159
3     21
2      7
1      6
5      1
Name: bars, dtype: int64

In [4]:
sigma = len(df)

P_A_and_B = len(df[(df['circles'] == 0) & (df['bars'] == 0)]) / sigma

P_B = df['bars'].value_counts()[0] / sigma

P_A_given_B = P_A_and_B / P_B
display(P_A_given_B)

0.8238993710691824

## Question 2

- Consider two random variables:
    + X: number of bars on the flag
    + Y: number of crosses on the flag
- Are they independent?

In [5]:
# Analyze
display(df['bars'].value_counts())
display(df['crosses'].value_counts())

0    159
3     21
2      7
1      6
5      1
Name: bars, dtype: int64

0    167
1     25
2      2
Name: crosses, dtype: int64

In [6]:
## Check dependence by pmf_XY

X = [0,1,2,3,5]
Y = [0,1,2]
sigma = len(df)

# P_X
P_X = np.array([df['bars'].value_counts()[x_i] / sigma for x_i in X])
display(P_X)

# P_Y
P_Y = np.array([df['crosses'].value_counts()[y_j] / sigma for y_j in Y])
display(P_Y)

# pmf_XY
pmf_XY = np.zeros((len(X), len(Y)), dtype=float)
for i in range(len(X)):
    for j in range(len(Y)):
        pmf_XY[i][j] = len(df[(df['bars'] == X[i]) & (df['crosses'] == Y[j])]) / sigma
display(pmf_XY)

# Check
results = np.zeros((len(X), len(Y)), dtype=float)
for i in range(len(X)):
    for j in range(len(Y)):
        results[i][j] = abs(pmf_XY[i][j] - P_X[i]*P_Y[j])
display(results)

array([0.81958763, 0.03092784, 0.03608247, 0.10824742, 0.00515464])

array([0.86082474, 0.12886598, 0.01030928])

array([[0.68556701, 0.12371134, 0.01030928],
       [0.03092784, 0.        , 0.        ],
       [0.03092784, 0.00515464, 0.        ],
       [0.10824742, 0.        , 0.        ],
       [0.00515464, 0.        , 0.        ]])

array([[1.99542991e-02, 1.80943777e-02, 1.85992135e-03],
       [4.30438941e-03, 3.98554575e-03, 3.18843660e-04],
       [1.32851525e-04, 5.04835796e-04, 3.71984270e-04],
       [1.50653630e-02, 1.39494101e-02, 1.11595281e-03],
       [7.17398236e-04, 6.64257626e-04, 5.31406101e-05]])

--> Not independent

## Question 3
- Find Pearson's correlation coefficient between area and population

In [7]:
df[['area', 'population']].corr()

area  population
area        1.00000     0.51903
population  0.51903     1.00000