In [1]:
import numpy as np
import torch

# Numpy

In [2]:
# flatten
a = np.random.random((1, 2, 3))
b = a.reshape(-1)

print(a.shape)
print(b.shape)

(1, 2, 3)
(6,)


In [3]:
# Add dimension
a = np.random.random((6,))
b = a.reshape(1, -1)

print(a.shape)
print(b.shape)

(6,)
(1, 6)


In [4]:
# -1: autofit dim
a = np.random.random((1, 2, 3))
b = a.reshape(-1, 3)

print(a.shape)
print(b.shape)

(1, 2, 3)
(2, 3)


# Torch 1 tensor ops

#### view (reshape)

In [5]:
# flatten
a = torch.rand((1, 2, 3))
b = a.view(-1)

print(a.shape)
print(b.shape)

torch.Size([1, 2, 3])
torch.Size([6])


In [6]:
# Add dimension
a = torch.rand(5)
print(a.size())

b = a.view(1, -1)
print(b.size())

torch.Size([5])
torch.Size([1, 5])


In [7]:
# -1: autofit dim
a = torch.rand(1,2,3)
b = a.view(-1, 2)

print(a.size())
print(b.size())

torch.Size([1, 2, 3])
torch.Size([3, 2])


#### Permute, transpose

In [8]:
# Permute: swap dimension
a = torch.rand(1,2,3)
b = a.permute(0, 2, 1)

print(a.size())
print(b.size())

torch.Size([1, 2, 3])
torch.Size([1, 3, 2])


In [9]:
# transpose - For 2D tensors only
a = torch.rand(2, 3)
print(a.size())

b = a.t()
print(b.size())

torch.Size([2, 3])
torch.Size([3, 2])


#### squeeze, unsqueeze

In [10]:
# squeeze
a = torch.rand(1,5) # (1,5)

print(a.squeeze().size())

torch.Size([5])


In [11]:
# unsqueeze
a = torch.rand(5) # (5)

print(a.unsqueeze(dim=0).size())
print(a.unsqueeze(dim=1).size())

torch.Size([1, 5])
torch.Size([5, 1])


#### repeat
- Repeat each dimension () time

In [12]:
a = torch.tensor([
    [1,2,3],
    [4,5,6]
]) # (2,3)

res = a.repeat(1,1)
print(res, res.size())

res = a.repeat(1,2)
print(res, res.size())

res = a.repeat(1,3)
print(res, res.size())

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]]) torch.Size([2, 6])
tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6]]) torch.Size([2, 9])


In [13]:
res = a.repeat(2,1)
print(res, res.size())

res = a.repeat(3,1)
print(res, res.size())

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]]) torch.Size([4, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]]) torch.Size([6, 3])


In [14]:
res = a.repeat(2,2)
print(res, res.size())

tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6],
        [1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]]) torch.Size([4, 6])


# Torch 2+ tensor ops

#### stack

In [15]:
a = torch.tensor([
    [1,2,3],
    [4,5,6]
]) # (2,3)
b = torch.Tensor([
    [11,12,13],
    [14,15,16]
]) # (2,3)


res = torch.stack([a,b], dim=0)
print(res, res.size())

res = torch.stack([a,b], dim=1)
print(res, res.size())

res = torch.stack([a,b], dim=2)
print(res, res.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[11., 12., 13.],
         [14., 15., 16.]]]) torch.Size([2, 2, 3])
tensor([[[ 1.,  2.,  3.],
         [11., 12., 13.]],

        [[ 4.,  5.,  6.],
         [14., 15., 16.]]]) torch.Size([2, 2, 3])
tensor([[[ 1., 11.],
         [ 2., 12.],
         [ 3., 13.]],

        [[ 4., 14.],
         [ 5., 15.],
         [ 6., 16.]]]) torch.Size([2, 3, 2])


#### concat

In [16]:
a = torch.tensor([
    [1,2,3],
    [4,5,6]
])
b = torch.Tensor([
    [11,12,13],
    [14,15,16]
])

res = torch.cat([a,b], dim=0)
print(res, res.size())

res = torch.cat([a,b], dim=1)
print(res, res.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [11., 12., 13.],
        [14., 15., 16.]]) torch.Size([4, 3])
tensor([[ 1.,  2.,  3., 11., 12., 13.],
        [ 4.,  5.,  6., 14., 15., 16.]]) torch.Size([2, 6])


## Save/Load tensor to a file

In [17]:
a = torch.rand(10, 3, 3)

In [18]:
# Save
torch.save(a, 'a_tensor.pt')

In [19]:
# Load
a_load = torch.load('a_tensor.pt')
print(a_load.size())

torch.Size([10, 3, 3])


# Calculate mean, var of a big dataset
#### Example 1: get mean, var along dim=2 (257)

In [20]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# Dataset
N = 1000
X = torch.randn(N, 1937, 257)
y = torch.randn(N, 1)

# Dataloader
dataset = TensorDataset(X, y)
loader = DataLoader(dataset, batch_size=8)

# Calc mean, var
mean = 0.0
variance = 0.0
N_ = 0
for Xb, yb in loader:
    N_ += Xb.size(0)
    mean += Xb.mean(1).sum(0) 
    variance += Xb.var(1).sum(0)

mean /= N_
variance /= N_

In [21]:
print(mean.size(), variance.size())

torch.Size([257]) torch.Size([257])


#### Example 2: get mean, var along C-dim of Image dataset (N, C, W, H)

In [22]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# Dataset
N = 1000
X = torch.randn(N, 3, 128, 128)
y = torch.randn(N, 1)

# Dataloader
dataset = TensorDataset(X, y)
loader = DataLoader(dataset, batch_size=8)

# Calc mean, std
mean = 0.0
std = 0.0
N_ = 0
for Xb, yb in loader:
    # Update total number of images
    N_ += Xb.size(0)

    # Rearrange batch to be the shape of [B, C, W * H]
    Xb = Xb.view(Xb.size(0), Xb.size(1), -1)

    # Compute mean and std here
    mean += Xb.mean(2).sum(0) 
    std += Xb.std(2).sum(0)

mean /= N_
std /= N_

In [23]:
print(mean.size(), std.size())

torch.Size([3]) torch.Size([3])
