In [1]:
from IPython.display import display

import pandas as pd
import numpy as np

# Array

#### Initialize

In [2]:
# Create an integer array of length 100 filled with zeros
np.zeros(100, dtype=int)

# Create a 3x3 floating-point array filled with 1s
np.ones((3, 3), dtype=float)

# Starting at 0, ending at 20, stepping by 3
np.arange(0, 20, 3)

# Create an array of n = 100, evenly spaced between 0 and 1
np.linspace(0, 1, 100)

# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

# Create a 3x3 array of normally distributed random values
# with mean=0 and std=1
np.random.normal(0, 1, (3, 3))

np.random.randint(10, size=6)  # 1D array of random integers
np.random.randint(10, size=(3, 3))  # 2D array of random integers
np.random.randint(10, size=(3, 3, 3))  # 3D array of random integers

array([[[7, 2, 2],
        [8, 8, 5],
        [9, 6, 0]],

       [[8, 8, 7],
        [3, 1, 9],
        [9, 4, 6]],

       [[9, 4, 1],
        [4, 6, 3],
        [0, 0, 3]]])

#### Attributes
- `ndim`: the number of dimensions
- `shape`: the size of each dimension
- `size`: the total size of the array
- `dtype`: the data type of the array
- `itemsize`: the size (in bytes) of each array element
- `nbytes`: the total size (in bytes) of the array

In [3]:
arr = np.array([0,1,2,3])

display(arr.ndim)
display(arr.shape)
display(arr.size)
display(arr.dtype.name)

1

(4,)

4

'int64'

In [4]:
arr = np.array([[0,1,2,3]])

display(arr.ndim)
display(arr.shape)
display(arr.size)
display(arr.dtype.name)

2

(1, 4)

4

'int64'

In [5]:
arr = np.array(
    [[0,1,2,3],
     [4,5,6,7],
     [8,9,10]])

display(arr.ndim)
display(arr.shape)
display(arr.size)
display(arr.dtype.name)

1

(3,)

3

'object'

In [6]:
arr = np.array(
    [[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]])

display(arr.ndim)
display(arr.shape)
display(arr.size)
display(arr.dtype.name)

2

(3, 4)

12

'int64'

#### Slicing

In [7]:
arr = np.array(
    [[ 1,  2,  3,  4,  5],
     [ 6,  7,  8,  9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20]])

# col
display(arr[:, 1])

# row
display(arr[0, :])

# range
display(arr[1:3, 2:4])

array([ 2,  7, 12, 17])

array([1, 2, 3, 4, 5])

array([[ 8,  9],
       [13, 14]])

#### Reshape

In [8]:
a = np.arange(1,10)
display(a)

b = a.reshape(3,3)
display(b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Reshape (,) to 1D
a = np.arange(1,10).reshape(3,3)
display(a)

b = a.flatten()
display(b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Functions

In [10]:
#!/usr/bin/env python3
import numpy as np

x = np.arange(10)
print("x =", x, end='\n\n')

# Native arithmentic operators
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 5 =", x * 5)
print("x / 5 =", x / 5)
print("x // 5 =", x // 5)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2, end='\n\n')

# OR we can use explicit functions, ufuncs, e.g. "add" instead of "+"
print("x + 5 =", np.add(x, 5))
print("x - 5 =", np.subtract(x, 5))
print("x * 5 =", np.multiply(x, 5))
print("x / 5 =", np.divide(x, 5))
print("x ** 2 = ", np.power(x, 2))
print("x % 2  = ", np.mod(x, 2))

x = [0 1 2 3 4 5 6 7 8 9]

x + 5 = [ 5  6  7  8  9 10 11 12 13 14]
x - 5 = [-5 -4 -3 -2 -1  0  1  2  3  4]
x * 5 = [ 0  5 10 15 20 25 30 35 40 45]
x / 5 = [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
x // 5 = [0 0 0 0 0 1 1 1 1 1]
x ** 2 =  [ 0  1  4  9 16 25 36 49 64 81]
x % 2  =  [0 1 0 1 0 1 0 1 0 1]

x + 5 = [ 5  6  7  8  9 10 11 12 13 14]
x - 5 = [-5 -4 -3 -2 -1  0  1  2  3  4]
x * 5 = [ 0  5 10 15 20 25 30 35 40 45]
x / 5 = [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
x ** 2 =  [ 0  1  4  9 16 25 36 49 64 81]
x % 2  =  [0 1 0 1 0 1 0 1 0 1]


In [11]:
# a,b must be same size
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([10,9,8,7,6,5,4,3,2,1])
print("a =", a)
print("b =", b, end='\n\n')

# Native arithmentic operators
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a // b =", a // b)
print("a ** b =", a ** b)
print("a % b  = ", a % b, end='\n\n')

# OR we can use explicit functions, ufuncs, e.g. "add" instead of "+"
print("a + b =", np.add(a, b))
print("a - b =", np.subtract(a, b))
print("a * b =", np.multiply(a, b))
print("a / b =", np.divide(a, b))
print("a ** b =", np.power(a, b))
print("a % b  = ", np.mod(a, b))

a = [ 1  2  3  4  5  6  7  8  9 10]
b = [10  9  8  7  6  5  4  3  2  1]

a + b = [11 11 11 11 11 11 11 11 11 11]
a - b = [-9 -7 -5 -3 -1  1  3  5  7  9]
a * b = [10 18 24 28 30 30 28 24 18 10]
a / b = [ 0.1         0.22222222  0.375       0.57142857  0.83333333  1.2
  1.75        2.66666667  4.5        10.        ]
a // b = [ 0  0  0  0  0  1  1  2  4 10]
a ** b = [    1   512  6561 16384 15625  7776  2401   512    81    10]
a % b  =  [1 2 3 4 5 1 3 2 1 0]

a + b = [11 11 11 11 11 11 11 11 11 11]
a - b = [-9 -7 -5 -3 -1  1  3  5  7  9]
a * b = [10 18 24 28 30 30 28 24 18 10]
a / b = [ 0.1         0.22222222  0.375       0.57142857  0.83333333  1.2
  1.75        2.66666667  4.5        10.        ]
a ** b = [    1   512  6561 16384 15625  7776  2401   512    81    10]
a % b  =  [1 2 3 4 5 1 3 2 1 0]


#### Reduce

In [12]:
x = np.arange(1, 6)
print(x)

sum_all = np.add.reduce(x)
print(sum_all)

[1 2 3 4 5]
15


#### Accumulate

In [13]:
x = np.arange(1, 6)
print(x)

sum_acc = np.add.accumulate(x)
print(sum_acc)

[1 2 3 4 5]
[ 1  3  6 10 15]


#### Aggregate 1D

In [14]:
x = np.random.randint(0, 10, (1, 10)).flatten()
print("x = ", x, end='\n\n')

# Agg 1
print("Sum of values is:", np.sum(x))
print("Mean value is: ", np.mean(x))

# Agg 2
print("Sum of values is:", x.sum())
print("Mean value is: ", x.mean())
print("Max value is: ", x.max())
print("Min value is: ", x.min())

# Agg 3
print("Max value index is:", x.argmax())
print("Min value index is:", x.argmin())

x =  [4 9 6 8 0 5 8 7 9 8]

Sum of values is: 64
Mean value is:  6.4
Sum of values is: 64
Mean value is:  6.4
Max value is:  9
Min value is:  0
Max value index is: 1
Min value index is: 4


#### Aggregate 2D

In [15]:
grid = np.random.random((3, 4))
print(grid)

# All
print("Overall sum:", grid.sum())
print("Overall Min:", grid.min())

# Row wise and column wise min
print("Column wise minimum: ", np.amin(grid, axis=0))
print("Row wise minimum: ", np.amin(grid, axis=1))

[[0.70607948 0.68175238 0.41217173 0.18636581]
 [0.21651035 0.06838999 0.61142227 0.12949048]
 [0.20863119 0.85397123 0.68107917 0.86005682]]
Overall sum: 5.615920895418759
Overall Min: 0.0683899930676879
Column wise minimum:  [0.20863119 0.06838999 0.41217173 0.12949048]
Row wise minimum:  [0.18636581 0.06838999 0.20863119]


# Boolean Masks

In [16]:
x = np.array([1, 2, 3, 4, 5])
print(x < 2)
print(x >= 4)

[ True False False False False]
[False False False  True  True]


In [17]:
# a,b must be same size
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([10,9,8,7,6,5,4,3,2,1])

print(a < b)

[ True  True  True  True  True False False False False False]


In [18]:
# a,b must be same size
a = np.array([True, False, True, False], dtype=bool)
b = np.array([True, True, False, False], dtype=bool)

print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))

[ True  True  True False]
[ True False False False]
[False  True False  True]


#### Count, Any, All

In [19]:
x = np.arange(10)
print(x)

# How many values less than 6?
print(np.count_nonzero(x < 6))

# Are there any values greater than 8?
print(np.any(x > 8))

# Are all values less than 10?
print(np.all(x < 10))

[0 1 2 3 4 5 6 7 8 9]
6
True
True


#### Filter

In [20]:
x = np.random.randint(0, 10, size=10)
print(x, end= '\n\n')

# List all x < 6
print(x[x < 6])

# List all x < 6 index
print(np.where(x < 6))

# List all x < 6 by where
print(x[np.where(x < 6)])

[8 9 8 8 3 0 6 3 6 8]

[3 0 3]
(array([4, 5, 7]),)
[3 0 3]


In [21]:
x = np.random.randint(0, 10, size=10)
print(x, end= '\n\n')

# List all 2 < x < 6
print(x[(2 < x) & (x < 6)])

# Replace all x < 6 = 100
x[x < 6] = 100
print(x)

[2 9 2 8 7 6 6 7 3 4]

[3 4]
[100   9 100   8   7   6   6   7 100 100]
